"use client";
import { FormEvent, useCallback, useEffect, useRef, useState } from "react";
import { useRouter } from "next/navigation";
import { createClient } from "@/lib/supabase/client";
import Header from "./Header";
import BottomNav from "./BottomNav";

type ScanResult={outcome:string;message:string;sign_in_id?:number;wasra_number?:number;competitor_name?:string;signed_in_at?:string;firearms_authority_display?:string;membership_status?:string;target_type?:string;distance?:string;shooting_class?:string;position?:string;d1?:number|null;d2?:number|null;d3?:number|null;d4?:number|null;volunteer_role?:string|null;volunteer_detail?:string|null;warning_code?:string|null};
type Roster={weekly_entry_id:number;wasra_number:number;competitor_name:string;d1:number|null;d2:number|null;d3:number|null;d4:number|null;volunteer_role:string|null;volunteer_detail:string|null;attendance_status:string;signed_in_at:string|null;warning_code:string|null};
export default function SignInApp(){
 const supabase=createClient(); const router=useRouter(); const inputRef=useRef<HTMLInputElement>(null); const [eventId,setEventId]=useState<number|null>(null); const [eventName,setEventName]=useState("Loading event"); const [eventDate,setEventDate]=useState(""); const [scan,setScan]=useState(""); const [result,setResult]=useState<ScanResult|null>(null); const [roster,setRoster]=useState<Roster[]>([]); const [busy,setBusy]=useState(false);
 const load=useCallback(async()=>{const {data:{user}}=await supabase.auth.getUser();if(!user){router.replace("/login");return}const pilot=process.env.NEXT_PUBLIC_PILOT_EVENT_DATE||"2026-08-20";const {data:event}=await supabase.from("events").select("id,name,event_date").eq("event_date",pilot).eq("sign_in_open",true).maybeSingle();if(!event){setEventName("No open event");return}setEventId(event.id);setEventName(event.name||"Weekly Event");setEventDate(event.event_date);const {data}=await supabase.from("app_sign_in_roster").select("*").eq("event_id",event.id).order("competitor_name");setRoster((data||[]) as Roster[])},[router,supabase]);
 useEffect(()=>{load();inputRef.current?.focus()},[load]);
 const totals={expected:roster.length,signed:roster.filter(x=>x.signed_in_at).length};
 async function submit(e:FormEvent){e.preventDefault();const value=scan.trim();if(!value||!eventId)return;setBusy(true);const {data,error}=await supabase.rpc("scan_member",{p_scanned_value:value,p_event_id:eventId});setBusy(false);setScan("");if(error)setResult({outcome:"error",message:error.message});else setResult(data as ScanResult);await load();setTimeout(()=>inputRef.current?.focus(),0)}
 async function undo(){if(!result?.sign_in_id)return;setBusy(true);const {data,error}=await supabase.rpc("undo_sign_in",{p_sign_in_id:result.sign_in_id});setBusy(false);setResult(error?{outcome:"error",message:error.message}:data as ScanResult);await load();inputRef.current?.focus()}
 function style(){if(!result)return "info";if(result.outcome==="signed_in")return "success";if(result.outcome==="signed_in_with_warning")return "warning";if(result.outcome==="already_signed_in"||result.outcome==="member_not_entered")return "info";return "error"}
 return <div className="shell" id="top"><Header eventName={eventName} eventDate={eventDate}/><main className="main"><div className="scan-label">Scan membership card</div><form className="scan-form" onSubmit={submit}><input ref={inputRef} className="scan-input" inputMode="numeric" autoComplete="off" placeholder="Scan card or enter WASRA number" value={scan} onChange={e=>setScan(e.target.value)} disabled={busy||!eventId}/><button className="primary" disabled={busy||!eventId}>{busy?"Working...":"Sign in"}</button></form><div className="hint">Scanner ready • Press Enter after manual entry</div>{result?<section className={`result ${style()}`}><div className="result-title">{result.outcome.replaceAll("_"," ").toUpperCase()}</div>{result.competitor_name&&<><div className="person">{result.competitor_name}</div><div className="muted">WASRA {result.wasra_number}</div></>}<p>{result.message}</p>{result.competitor_name&&<><div className="facts"><div className="fact"><small>SHOOTING ENTRY</small>{[result.target_type==="E"?"Electronic":"Paper",result.distance,result.shooting_class].filter(Boolean).join(" • ")}</div><div className="fact"><small>VOLUNTEER DUTY</small>{[result.volunteer_role,result.volunteer_detail].filter(Boolean).join(" • ")||"None"}</div></div><div className="grid">{([1,2,3,4] as const).map(n=><div className="bay" key={n}>D{n}<b>{result[`d${n}`]??"–"}</b></div>)}</div><div className="facts"><div className="fact"><small>FAL STATUS</small>{result.firearms_authority_display||"Unknown"}</div><div className="fact"><small>MEMBERSHIP</small>{result.membership_status||"Unknown"}</div></div></>}{result.sign_in_id&&result.outcome.startsWith("signed_in")&&<div className="actions"><button className="danger" onClick={undo} disabled={busy}>Undo sign-in</button></div>}</section>:<section className="result info"><div className="result-title">READY</div><p>Waiting for the next membership card.</p></section>}<section className="stats"><div className="stat"><b>{totals.signed}</b><span>SIGNED IN</span></div><div className="stat"><b>{totals.expected-totals.signed}</b><span>REMAINING</span></div><div className="stat"><b>{totals.expected}</b><span>EXPECTED</span></div></section><div className="section-head"><h3>Recent sign-ins</h3><a href="/attendance">View all</a></div><div className="list">{roster.filter(x=>x.signed_in_at).sort((a,b)=>(b.signed_in_at||"").localeCompare(a.signed_in_at||"")).slice(0,5).map(x=><div className="row" key={x.weekly_entry_id}><div className="row-main"><div className="row-name">{x.competitor_name}</div><div className="row-meta">WASRA {x.wasra_number} • Bays {[x.d1,x.d2,x.d3,x.d4].map(v=>v??"–").join("/")}</div></div><div className="status good">SIGNED IN</div></div>)}{!roster.some(x=>x.signed_in_at)&&<p className="muted">No sign-ins yet.</p>}</div></main><BottomNav active="scan"/></div>
}
